### ISSUE TITLE
Possible confusion: backslash vs backspace

### ISSUE THREAD

**Issue by Haroenv** [JohMun/vue-tags-input#59]
Looks like you're documenting and internally using the word "backslash", however I think you might mean "backspace". 

Backslash is this character: `\`
Backspace is not printable, but it's the character on top of the enter/return key 

more info on backspace: https://en.wikipedia.org/wiki/Backspace

I might look how much of backslash is public API too to change it without breaking change (or release as a new major)

**Comment by JohMun** [comment]
Whoops, you are right. Incredible that nobody noticed this before, including myself. I am currently working  on a new [version](https://github.com/JohMun/vue-tags-input/tree/v2), where this issue can be fixed, because it's a breaking change (even if it's a small one). There will be a release in the next 2~3 weeks. Thx for reporting this!

**Comment by Haroenv** [comment]
All right, I'll let you deal with this then!

**Comment by JohMun** [comment]
[Version 2](https://github.com/JohMun/vue-tags-input/releases/tag/v2.0.0) is now available and 'backslash' has been replaced with 'backspace'
